/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.languages.autoresponder.parser.antlr.internal.InternalAutoResponderParser;
import uk.ac.kcl.inf.languages.autoresponder.services.AutoResponderGrammarAccess;

public class AutoResponderParser extends AbstractAntlrParser {

	@Inject
	private AutoResponderGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAutoResponderParser createParser(XtextTokenStream stream) {
		return new InternalAutoResponderParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AutoResponderProgram";
	}

	public AutoResponderGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AutoResponderGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
