/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Activity Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getLast_input <em>Last input</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getActivityStatement()
 * @model
 * @generated
 */
public interface ActivityStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getActivityStatement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Last input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Last input</em>' containment reference.
   * @see #setLast_input(StringExpression)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getActivityStatement_Last_input()
   * @model containment="true"
   * @generated
   */
  StringExpression getLast_input();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getLast_input <em>Last input</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Last input</em>' containment reference.
   * @see #getLast_input()
   * @generated
   */
  void setLast_input(StringExpression value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getActivityStatement_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // ActivityStatement
