/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderFactory
 * @model kind="package"
 * @generated
 */
public interface AutoResponderPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "autoResponder";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/languages/autoresponder/AutoResponder";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "autoResponder";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AutoResponderPackage eINSTANCE = uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderProgramImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getAutoResponderProgram()
   * @generated
   */
  int AUTO_RESPONDER_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTO_RESPONDER_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTO_RESPONDER_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StatementImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.HearStatementImpl <em>Hear Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.HearStatementImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getHearStatement()
   * @generated
   */
  int HEAR_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEAR_STATEMENT__VALUE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Hear Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEAR_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.VariableDeclarationImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringExpressionImpl <em>String Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringExpressionImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStringExpression()
   * @generated
   */
  int STRING_EXPRESSION = 7;

  /**
   * The number of structural features of the '<em>String Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringLiteralImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 4;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__VAL = STRING_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = STRING_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringVariableDeclarationImpl <em>String Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringVariableDeclarationImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStringVariableDeclaration()
   * @generated
   */
  int STRING_VARIABLE_DECLARATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VARIABLE_DECLARATION__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VARIABLE_DECLARATION__STRING = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>String Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VARIABLE_DECLARATION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringVarExpressionImpl <em>String Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringVarExpressionImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStringVarExpression()
   * @generated
   */
  int STRING_VAR_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VAR_EXPRESSION__VAR = STRING_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VAR_EXPRESSION_FEATURE_COUNT = STRING_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.TriggerStatementImpl <em>Trigger Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.TriggerStatementImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getTriggerStatement()
   * @generated
   */
  int TRIGGER_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Activity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_STATEMENT__ACTIVITY = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_STATEMENT__STATEMENT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Trigger Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ActivityStatementImpl <em>Activity Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ActivityStatementImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getActivityStatement()
   * @generated
   */
  int ACTIVITY_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Last input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_STATEMENT__LAST_INPUT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_STATEMENT__STATEMENTS = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Activity Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIVITY_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.InstructStatementImpl <em>Instruct Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.InstructStatementImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getInstructStatement()
   * @generated
   */
  int INSTRUCT_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>Instruction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCT_STATEMENT__INSTRUCTION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Instruct Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCT_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.TerminationStatementImpl <em>Termination Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.TerminationStatementImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getTerminationStatement()
   * @generated
   */
  int TERMINATION_STATEMENT = 11;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATION_STATEMENT__STATE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Termination Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATION_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ContactStatementImpl <em>Contact Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ContactStatementImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getContactStatement()
   * @generated
   */
  int CONTACT_STATEMENT = 12;

  /**
   * The feature id for the '<em><b>Phone Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTACT_STATEMENT__PHONE_NUMBER = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Contact Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTACT_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ExpressionImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 13;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.IntLiteralImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 14;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.RealLiteralImpl <em>Real Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.RealLiteralImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getRealLiteral()
   * @generated
   */
  int REAL_LITERAL = 15;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Real Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.IntVarExpressionImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 16;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AdditionImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.MultiplicationImpl
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState <em>Activity State</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getActivityState()
   * @generated
   */
  int ACTIVITY_STATE = 19;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderProgram
   * @generated
   */
  EClass getAutoResponderProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderProgram#getStatements()
   * @see #getAutoResponderProgram()
   * @generated
   */
  EReference getAutoResponderProgram_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.HearStatement <em>Hear Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hear Statement</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.HearStatement
   * @generated
   */
  EClass getHearStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.HearStatement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.HearStatement#getValue()
   * @see #getHearStatement()
   * @generated
   */
  EAttribute getHearStatement_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringLiteral#getVal()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration <em>String Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Variable Declaration</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration
   * @generated
   */
  EClass getStringVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration#getName()
   * @see #getStringVariableDeclaration()
   * @generated
   */
  EAttribute getStringVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration#getString()
   * @see #getStringVariableDeclaration()
   * @generated
   */
  EAttribute getStringVariableDeclaration_String();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVarExpression <em>String Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Var Expression</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVarExpression
   * @generated
   */
  EClass getStringVarExpression();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVarExpression#getVar()
   * @see #getStringVarExpression()
   * @generated
   */
  EReference getStringVarExpression_Var();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringExpression <em>String Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Expression</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringExpression
   * @generated
   */
  EClass getStringExpression();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement <em>Trigger Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger Statement</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement
   * @generated
   */
  EClass getTriggerStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getName()
   * @see #getTriggerStatement()
   * @generated
   */
  EAttribute getTriggerStatement_Name();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getActivity <em>Activity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Activity</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getActivity()
   * @see #getTriggerStatement()
   * @generated
   */
  EReference getTriggerStatement_Activity();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getStatement()
   * @see #getTriggerStatement()
   * @generated
   */
  EReference getTriggerStatement_Statement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement <em>Activity Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Activity Statement</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement
   * @generated
   */
  EClass getActivityStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getName()
   * @see #getActivityStatement()
   * @generated
   */
  EAttribute getActivityStatement_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getLast_input <em>Last input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Last input</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getLast_input()
   * @see #getActivityStatement()
   * @generated
   */
  EReference getActivityStatement_Last_input();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement#getStatements()
   * @see #getActivityStatement()
   * @generated
   */
  EReference getActivityStatement_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.InstructStatement <em>Instruct Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruct Statement</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.InstructStatement
   * @generated
   */
  EClass getInstructStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.InstructStatement#getInstruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Instruction</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.InstructStatement#getInstruction()
   * @see #getInstructStatement()
   * @generated
   */
  EReference getInstructStatement_Instruction();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TerminationStatement <em>Termination Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Termination Statement</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.TerminationStatement
   * @generated
   */
  EClass getTerminationStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TerminationStatement#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.TerminationStatement#getState()
   * @see #getTerminationStatement()
   * @generated
   */
  EAttribute getTerminationStatement_State();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ContactStatement <em>Contact Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contact Statement</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ContactStatement
   * @generated
   */
  EClass getContactStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ContactStatement#getPhoneNumber <em>Phone Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Phone Number</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ContactStatement#getPhoneNumber()
   * @see #getContactStatement()
   * @generated
   */
  EReference getContactStatement_PhoneNumber();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.RealLiteral <em>Real Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Literal</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.RealLiteral
   * @generated
   */
  EClass getRealLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.RealLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.RealLiteral#getVal()
   * @see #getRealLiteral()
   * @generated
   */
  EAttribute getRealLiteral_Val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState <em>Activity State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Activity State</em>'.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState
   * @generated
   */
  EEnum getActivityState();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AutoResponderFactory getAutoResponderFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderProgramImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getAutoResponderProgram()
     * @generated
     */
    EClass AUTO_RESPONDER_PROGRAM = eINSTANCE.getAutoResponderProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTO_RESPONDER_PROGRAM__STATEMENTS = eINSTANCE.getAutoResponderProgram_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StatementImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.HearStatementImpl <em>Hear Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.HearStatementImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getHearStatement()
     * @generated
     */
    EClass HEAR_STATEMENT = eINSTANCE.getHearStatement();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEAR_STATEMENT__VALUE = eINSTANCE.getHearStatement_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.VariableDeclarationImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringLiteralImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__VAL = eINSTANCE.getStringLiteral_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringVariableDeclarationImpl <em>String Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringVariableDeclarationImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStringVariableDeclaration()
     * @generated
     */
    EClass STRING_VARIABLE_DECLARATION = eINSTANCE.getStringVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VARIABLE_DECLARATION__NAME = eINSTANCE.getStringVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VARIABLE_DECLARATION__STRING = eINSTANCE.getStringVariableDeclaration_String();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringVarExpressionImpl <em>String Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringVarExpressionImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStringVarExpression()
     * @generated
     */
    EClass STRING_VAR_EXPRESSION = eINSTANCE.getStringVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRING_VAR_EXPRESSION__VAR = eINSTANCE.getStringVarExpression_Var();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringExpressionImpl <em>String Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.StringExpressionImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getStringExpression()
     * @generated
     */
    EClass STRING_EXPRESSION = eINSTANCE.getStringExpression();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.TriggerStatementImpl <em>Trigger Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.TriggerStatementImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getTriggerStatement()
     * @generated
     */
    EClass TRIGGER_STATEMENT = eINSTANCE.getTriggerStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER_STATEMENT__NAME = eINSTANCE.getTriggerStatement_Name();

    /**
     * The meta object literal for the '<em><b>Activity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER_STATEMENT__ACTIVITY = eINSTANCE.getTriggerStatement_Activity();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER_STATEMENT__STATEMENT = eINSTANCE.getTriggerStatement_Statement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ActivityStatementImpl <em>Activity Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ActivityStatementImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getActivityStatement()
     * @generated
     */
    EClass ACTIVITY_STATEMENT = eINSTANCE.getActivityStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTIVITY_STATEMENT__NAME = eINSTANCE.getActivityStatement_Name();

    /**
     * The meta object literal for the '<em><b>Last input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTIVITY_STATEMENT__LAST_INPUT = eINSTANCE.getActivityStatement_Last_input();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTIVITY_STATEMENT__STATEMENTS = eINSTANCE.getActivityStatement_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.InstructStatementImpl <em>Instruct Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.InstructStatementImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getInstructStatement()
     * @generated
     */
    EClass INSTRUCT_STATEMENT = eINSTANCE.getInstructStatement();

    /**
     * The meta object literal for the '<em><b>Instruction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCT_STATEMENT__INSTRUCTION = eINSTANCE.getInstructStatement_Instruction();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.TerminationStatementImpl <em>Termination Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.TerminationStatementImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getTerminationStatement()
     * @generated
     */
    EClass TERMINATION_STATEMENT = eINSTANCE.getTerminationStatement();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERMINATION_STATEMENT__STATE = eINSTANCE.getTerminationStatement_State();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ContactStatementImpl <em>Contact Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ContactStatementImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getContactStatement()
     * @generated
     */
    EClass CONTACT_STATEMENT = eINSTANCE.getContactStatement();

    /**
     * The meta object literal for the '<em><b>Phone Number</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTACT_STATEMENT__PHONE_NUMBER = eINSTANCE.getContactStatement_PhoneNumber();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ExpressionImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.IntLiteralImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.RealLiteralImpl <em>Real Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.RealLiteralImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getRealLiteral()
     * @generated
     */
    EClass REAL_LITERAL = eINSTANCE.getRealLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REAL_LITERAL__VAL = eINSTANCE.getRealLiteral_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.IntVarExpressionImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AdditionImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.MultiplicationImpl
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState <em>Activity State</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState
     * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.AutoResponderPackageImpl#getActivityState()
     * @generated
     */
    EEnum ACTIVITY_STATE = eINSTANCE.getActivityState();

  }

} //AutoResponderPackage
