/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contact Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ContactStatement#getPhoneNumber <em>Phone Number</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getContactStatement()
 * @model
 * @generated
 */
public interface ContactStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Phone Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phone Number</em>' containment reference.
   * @see #setPhoneNumber(StringExpression)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getContactStatement_PhoneNumber()
   * @model containment="true"
   * @generated
   */
  StringExpression getPhoneNumber();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ContactStatement#getPhoneNumber <em>Phone Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phone Number</em>' containment reference.
   * @see #getPhoneNumber()
   * @generated
   */
  void setPhoneNumber(StringExpression value);

} // ContactStatement
