/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getStringExpression()
 * @model
 * @generated
 */
public interface StringExpression extends EObject
{
} // StringExpression
