/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration#getString <em>String</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getStringVariableDeclaration()
 * @model
 * @generated
 */
public interface StringVariableDeclaration extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getStringVariableDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getStringVariableDeclaration_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVariableDeclaration#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

} // StringVariableDeclaration
