/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Var Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVarExpression#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getStringVarExpression()
 * @model
 * @generated
 */
public interface StringVarExpression extends StringExpression
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(StringVariableDeclaration)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getStringVarExpression_Var()
   * @model
   * @generated
   */
  StringVariableDeclaration getVar();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringVarExpression#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(StringVariableDeclaration value);

} // StringVarExpression
