/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termination Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TerminationStatement#getState <em>State</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getTerminationStatement()
 * @model
 * @generated
 */
public interface TerminationStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>State</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' attribute.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState
   * @see #setState(ActivityState)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getTerminationStatement_State()
   * @model
   * @generated
   */
  ActivityState getState();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TerminationStatement#getState <em>State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' attribute.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityState
   * @see #getState()
   * @generated
   */
  void setState(ActivityState value);

} // TerminationStatement
