/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigger Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getActivity <em>Activity</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getTriggerStatement()
 * @model
 * @generated
 */
public interface TriggerStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getTriggerStatement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Activity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activity</em>' reference.
   * @see #setActivity(ActivityStatement)
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getTriggerStatement_Activity()
   * @model
   * @generated
   */
  ActivityStatement getActivity();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.TriggerStatement#getActivity <em>Activity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activity</em>' reference.
   * @see #getActivity()
   * @generated
   */
  void setActivity(ActivityStatement value);

  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference list.
   * @see uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage#getTriggerStatement_Statement()
   * @model containment="true"
   * @generated
   */
  EList<ActivityStatement> getStatement();

} // TriggerStatement
