/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AutoResponderUiModule extends AbstractAutoResponderUiModule {

	public AutoResponderUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
