/**
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uk.ac.kcl.inf.languages.autoresponder.autoResponder.ActivityStatement;
import uk.ac.kcl.inf.languages.autoresponder.autoResponder.AutoResponderPackage;
import uk.ac.kcl.inf.languages.autoresponder.autoResponder.Statement;
import uk.ac.kcl.inf.languages.autoresponder.autoResponder.StringExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Activity Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ActivityStatementImpl#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ActivityStatementImpl#getLast_input <em>Last input</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.languages.autoresponder.autoResponder.impl.ActivityStatementImpl#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActivityStatementImpl extends StatementImpl implements ActivityStatement
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getLast_input() <em>Last input</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLast_input()
   * @generated
   * @ordered
   */
  protected StringExpression last_input;

  /**
   * The cached value of the '{@link #getStatements() <em>Statements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatements()
   * @generated
   * @ordered
   */
  protected EList<Statement> statements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActivityStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AutoResponderPackage.Literals.ACTIVITY_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AutoResponderPackage.ACTIVITY_STATEMENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringExpression getLast_input()
  {
    return last_input;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLast_input(StringExpression newLast_input, NotificationChain msgs)
  {
    StringExpression oldLast_input = last_input;
    last_input = newLast_input;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT, oldLast_input, newLast_input);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLast_input(StringExpression newLast_input)
  {
    if (newLast_input != last_input)
    {
      NotificationChain msgs = null;
      if (last_input != null)
        msgs = ((InternalEObject)last_input).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT, null, msgs);
      if (newLast_input != null)
        msgs = ((InternalEObject)newLast_input).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT, null, msgs);
      msgs = basicSetLast_input(newLast_input, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT, newLast_input, newLast_input));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Statement> getStatements()
  {
    if (statements == null)
    {
      statements = new EObjectContainmentEList<Statement>(Statement.class, this, AutoResponderPackage.ACTIVITY_STATEMENT__STATEMENTS);
    }
    return statements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT:
        return basicSetLast_input(null, msgs);
      case AutoResponderPackage.ACTIVITY_STATEMENT__STATEMENTS:
        return ((InternalEList<?>)getStatements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AutoResponderPackage.ACTIVITY_STATEMENT__NAME:
        return getName();
      case AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT:
        return getLast_input();
      case AutoResponderPackage.ACTIVITY_STATEMENT__STATEMENTS:
        return getStatements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AutoResponderPackage.ACTIVITY_STATEMENT__NAME:
        setName((String)newValue);
        return;
      case AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT:
        setLast_input((StringExpression)newValue);
        return;
      case AutoResponderPackage.ACTIVITY_STATEMENT__STATEMENTS:
        getStatements().clear();
        getStatements().addAll((Collection<? extends Statement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AutoResponderPackage.ACTIVITY_STATEMENT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT:
        setLast_input((StringExpression)null);
        return;
      case AutoResponderPackage.ACTIVITY_STATEMENT__STATEMENTS:
        getStatements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AutoResponderPackage.ACTIVITY_STATEMENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AutoResponderPackage.ACTIVITY_STATEMENT__LAST_INPUT:
        return last_input != null;
      case AutoResponderPackage.ACTIVITY_STATEMENT__STATEMENTS:
        return statements != null && !statements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ActivityStatementImpl
