/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.languages.autoresponder.ui.internal.AutoresponderActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AutoResponderExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AutoresponderActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AutoresponderActivator activator = AutoresponderActivator.getInstance();
		return activator != null ? activator.getInjector(AutoresponderActivator.UK_AC_KCL_INF_LANGUAGES_AUTORESPONDER_AUTORESPONDER) : null;
	}

}
