/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.languages.autoresponder.ui.internal.AutoresponderActivator;

public class AutoResponderUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AutoresponderActivator.getInstance().getInjector("uk.ac.kcl.inf.languages.autoresponder.AutoResponder");
	}

}
