/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder.ide;


/**
 * Use this class to register ide components.
 */
public class AutoResponderIdeModule extends AbstractAutoResponderIdeModule {
}
