/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AutoResponderStandaloneSetup extends AutoResponderStandaloneSetupGenerated {

	public static void doSetup() {
		new AutoResponderStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
