/*
 * generated by Xtext 2.26.0
 */
package uk.ac.kcl.inf.languages.autoresponder;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AutoResponderRuntimeModule extends AbstractAutoResponderRuntimeModule {
}
